### ISSUE TITLE
Up_Down_VC downstream task

### ISSUE THREAD

**Issue by windspirit95** [Wangt-CN/VC-R-CNN#10]
Hi,
Thank you for such a great open-source here.
I have succeeded in making an inference to the raw image base on ruotianluo 's codebase.
I am also interest on using your VC Feature there, so I guess it will work with VC concatenated with UpDown Feature on MSCOCO dataset.
About raw data inference, it is mentioned by ruotianluo that it will not work with UpDown Feature. Therefore, is it possible to concatenate your VC Feature with the pre-trained ResNet features, or we should use another mechanism? Thank you very much.

**Comment by Wangt-CN** [comment]
Actually, for

**Comment by Wangt-CN** [comment]
Actually the raw image can not work with updown feature is because the image should be firstly extracted the Updown feature. You can just get the updown feature firstly.
About concatenating to the pretrained resnet feature, the answer is absolutely yes. But I haven't done the experiment.

**Comment by Wangt-CN** [comment]
For the updown feature, you can refer to [here](https://github.com/peteanderson80/bottom-up-attention)

**Comment by Wangt-CN** [comment]
Moreover, the feature concatenation actually is very free. You can just treat VC feature as an additional information source and design models to use it.

**Comment by windspirit95** [comment]
Thank you, I will try it and let you know soon ^^
