### ISSUE TITLE
Where "last_checkpoint" should be modified to reflect the absolute path of "model_final.pth"?

### ISSUE THREAD

**Issue by amanchadha** [Wangt-CN/VC-R-CNN#6]
>>> "2. Using our pretrained VC model on COCO
>>>
>>> Here we also provide our pretrained VC model. You can put it into the model dictionary and set the last_checkpoint with the absolute path of model_final.pth. Then run the command:
>>>
>>> python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/test_net.py --config-file "path/to/config/file.yaml" TEST.IMS_PER_BA"

Can you please describe where "last_checkpoint" should be modified to reflect the absolute path of "model_final.pth"?

**Comment by Wangt-CN** [comment]
Sorry for the late reply. 
Actually if you train the model, the network would save the model in the set dictionary and create the 'last_checkpoint' file. 
For user who want directly use test file, I would upload this file later. Or you can just create one and the content is just the absolute path of model_final.pth.
