### ISSUE TITLE
Can you kindly provide VC features on VCR dataset?

### ISSUE THREAD

**Issue by tuyunbin** [Wangt-CN/VC-R-CNN#7]
Sir, thank you for your great work and it insights me a lot. My current reaseach topic is visual commonsense reasoning, so I hope you can kindly provide extracted VC features on VCR dataset for me.

**Comment by Wangt-CN** [comment]
Hi, thanks for your interest and sorry for the late reply. For the VCR dataset, you can just use our test file to extract the vc feature with your own bounding box coordinate file （Now there are many different bounding box settings for VCR dataset）. You can refer to [here](https://github.com/Wangt-CN/VC-R-CNN#evaluation-feature-extraction)
