### ISSUE TITLE
_C.DIC_FILE not found when run test_net.py

### ISSUE THREAD

**Issue by windspirit95** [Wangt-CN/VC-R-CNN#8]
Hi,
Thank you for your great work.
I have read your tutorial to run the test_net.py. However, I don't know how to get the pre-prepared dictionary file path for intervention (numpy format) (default is: '/.../dic_coco.npy')
So could you please guide me where could I download these files in Parameters of VC and change the directory? Thank you.

**Comment by Wangt-CN** [comment]
Hi,
Thanks for your attention. Then dic_coco.npy is in the folder `tools`. (https://github.com/Wangt-CN/VC-R-CNN/tree/master/tools)

**Comment by Wangt-CN** [comment]
Or do you want to change the parameters?
It's in the [`default.py`](https://github.com/Wangt-CN/VC-R-CNN/blob/master/vc_rcnn/config/defaults.py#L479)

**Comment by windspirit95** [comment]
Ah my mistake. Sorry I found it. Thank you.
